### ISSUE TITLE
Exposing allure object into karma

### ISSUE THREAD

**Issue by aolson58** [allure-framework/allure-karma#5]
I'm having trouble with my karma config exposing the allure global object to tests. Technically i use typescript but i should be able to retrofit an example of said exposure into karma regardless of source system.

**Comment by just-boris** [comment]
Karma runs code in a real browser, however reporting part run in node.js server-side.
There is a communication channel, that we are using. Basically, we are loading [this file](https://github.com/allure-framework/allure-karma/blob/master/client/allure.js) before your test code.

So, this is the global `allure` object that you will receive
