### ISSUE TITLE
No feature or story generated

### ISSUE THREAD

**Issue by mandalm** [allure-framework/allure-karma#6]
Hi team,

I am using this module to generate test report with karma. I am using jasmine for test with karma. Report generated successfully, however i notice that when i go to Behavior i see that no Feature and story created. 

I don't know whether its a bug or i missed something.

Can you please guide me how i can create / generate Feature and Story to be there? Also i see that in XML file  steps and attachments are blank.

<img width="1189" alt="screen shot 2017-03-02 at 12 27 57 pm" src="https://cloud.githubusercontent.com/assets/16209966/23496479/6ff9778e-ff44-11e6-8040-bb05114572e0.png">

Thanks and regards
Mithun Mandal

**Comment by mandalm** [comment]
Hi team,

I also gone through https://github.com/allure-examples/allure-karma-example i don't know whether i can directly use this. I am also using webpack with karma.

Please help.

regards
Mithun Mandal

**Comment by just-boris** [comment]
Hello!
You can try to do the following

```
it('is a test', () => {
})
```

**Comment by mandalm** [comment]
Thanks it worked. Also can you tell me when to use ```description```, ```createStep```, ```addEnvironment```, ```addArgument``` as they are not going to show in allure UI.  can i make use them like 

description  -> test description,
addEnvironment -> browser UA + OS, build version,
addArgument -> not sure, but like browser UA

how createStep will be useful?

regards
Mithun Mandal
